### ISSUE TITLE
The val result during train and test is different

### ISSUE THREAD

**Issue by jiujiuwei** [mit-han-lab/efficientvit#47]
I am training the b1_224 cls model, but I am encountering some issues. The results during training and testing are different. The validation dataset used for training is the same as the test dataset used for testing, and this is confusing me.

Here are the command and result screenshots. 
python eval_cls_model.py --mode b1 --weight_url exp12/cls/imagenet/b1_r224/checkpoint/model_best.pt 

<img width="196" alt="test result" src="https://github.com/mit-han-lab/efficientvit/assets/99394693/9290d77e-cef8-4396-9a20-68ba46b8be56">

torchpack dist-run -np 4  python train_cls_model.py configs/cls/imagenet/b1.yaml --path  exp12/cls/imagenet/b1_r224   

<img width="528" alt="train result" src="https://github.com/mit-han-lab/efficientvit/assets/99394693/a8ed84d2-43d0-4384-bcfe-bad13f114d98">

**Comment by han-cai** [comment]
Hi Jiang,

The code evaluates the ema model during training:
https://github.com/mit-han-lab/efficientvit/blob/2e967494483a9d47f31ae07f2b78e52fce254f68/efficientvit/apps/trainer/base.py#L41

If you directly feed the saved checkpoint to `eval_cls_model.py,` it will evaluate the original mode instead of the ema model. 

That's why the validation results are different. To get consistent results, you need to export the ema model from the saved checkpoint. 

Best,
Han
