### ISSUE TITLE
Replace yolov7 backbone, why do Nans and zeros occur when training under torch.cuda.amp?

### ISSUE THREAD

**Issue by liiicon** [mit-han-lab/efficientvit#7]

**Comment by han-cai** [comment]
Hi,

Thank you for reporting the issue. This problem might be due to this line:
https://github.com/mit-han-lab/efficientvit/blob/60ff616625a3b721bb462a045e008af769269444/models/nn/ops.py#L324

After replacing eps from 1e-15 to 1e-5, I can successfully train models under torch.cuda.amp in my experiments. 

Best regards,
Han

**Comment by han-cai** [comment]
This problem can be solved by adding the following line:
https://github.com/mit-han-lab/efficientvit/blob/a552d04e664f828b9981623f4b152f6226be8d60/efficientvit/models/nn/ops.py#L295
